apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
spec:
  project: jupyter
  source:
    repoURL: https://github.com/s-frw/homelab.git
    targetRevision: main
    path: argocd/helm-charts/jupyterhub
    helm:
      valueFiles:
        - ../../../helm-values/jupyterhub-values.yaml
      releaseName: jupyterhub
  destination:
    server: https://kubernetes.default.svc
    namespace: jupyter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

