apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterhub
  namespace: argocd
spec:
  project: jupyter
  source:
    repoURL: https://github.com/s-frw/homelab.git
    targetRevision: main
    path: argocd/apps/jupyterhub
    helm:
      valueFiles:
        - ../helm-values/jupyterhub-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jupyter
  syncPolicy:
    automated:
      prune: false  
      selfHeal: true

